### ISSUE TITLE
Cartogram of countries of the world display error

### ISSUE THREAD

**Issue by benhosken** [shawnbot/d3-cartogram#12]
When creating a cartogram for the countries of the world, countries sitting on or passing through the right side of the map e.g. 180deg distort when the cartogram is created. 

It appears that the geometry array that is created has negative (or zero) values for components of the features path and this is causing the display issue. 

I have created a cut down example at http://flinklabs.com/labs/worldcarto/ which highlights the issue. 

It is possible to partially correct this by overwriting the values for Russia and Fiji but this is not perfect nor ideal.

**Comment by shaliniravi** [comment]
Hello Everyone, 

I am new to d3.js. I am trying to understand the cartogram for world map. Like mentioned here, my cartogram also has lines (Russia). Can anyone tell me what is the solution for this :  http://stackoverflow.com/questions/29787205/how-to-remove-lines-in-between-cartogram-maps-in-d3-js

**Comment by shaliniravi** [comment]
@benhosken Did u find any solution for this issue ?

**Comment by benhosken** [comment]
We did find a solution to this which involved manually editing the json map in QGis. The issue was caused with arcs that went from 180 or maybe 360 to 0 basically when they wrapped around the edge. 

Because we were creating a cartogram, the accuracy of the shape was not a problem when we had a tiny section of an island cut off. 

I've answered the StackOverflow question with an example JSON file we used. 

We also simplified the map as we needed to create real time cartograms and then convert them into a hexagonal representation in the browser. Pushing the boundaries quite a bit but it did work. 

Let me know if you have problems with it.  

Ben Hosken
Founder
Flink Labs
www.flinklabs.com
@flinklabs
03 9018 5017

Flink is clever





On 24/04/2015, at 8:21 AM, Shalini Ravishankar <notifications@github.com> wrote:

Hello Everyone,

I am new to d3.js. I am trying to understand the cartogram for world map. Like mentioned here, my cartogram also has lines (Russia). Can anyone tell me what is the solution for this : http://stackoverflow.com/questions/29787205/how-to-remove-lines-in-between-cartogram-maps-in-d3-js

**Comment by alexlouden** [comment]
Hey @shaliniravi,

I've been building a cartogram of the world, and solved it a different way from @benhosken. I used https://github.com/mbostock/world-atlas, and modified the Makefile to add `--stitch-poles false`. That section now looks like:

```
topo/world-%.json: shp/ne_%_admin_0_countries.shp
	mkdir -p $(dir $@)
	$(TOPOJSON) \
		--quantization 1e5 \
		--stitch-poles false \
		--id-property=+iso_n3 \
		-- countries=shp/ne_$*_admin_0_countries.shp \
		| $(TOPOMERGE) \
			-o $@ \
			--io=countries \
			--oo=land \
			--no-key
```

Then when I ran `make topo/world-110m.json` I got [this file](http://population-forecast.herokuapp.com/world-110m-nostitch.json), which has the Chukchi Peninsula (and a tiny bit of Fiji) as separate polygons. 

Hope this helps!

**Comment by shaliniravi** [comment]
I understood. It works fine now :) Thank You Guys 😊 







-- 
Thanks & Regards,
Shalini Ravishankar





From: Alex Louden
Sent: ‎Thursday‎, ‎April‎ ‎23‎, ‎2015 ‎10‎:‎02‎ ‎PM
To: shawnbot/d3-cartogram
Cc: Shalini Ravishankar





Hey @shaliniravi,

I've been building a cartogram of the world, and solved it a different way from @benhosken. I used https://github.com/mbostock/world-atlas, and modified the Makefile to add --stitch-poles false. That section now looks like:
topo/world-%.json: shp/ne_%_admin_0_countries.shp
    mkdir -p $(dir $@)
    $(TOPOJSON) \
        --quantization 1e5 \
        --stitch-poles false \
        --id-property=+iso_n3 \
        -- countries=shp/ne_$*_admin_0_countries.shp \
        | $(TOPOMERGE) \
            -o $@ \
            --io=countries \
            --oo=land \
            --no-key


Then when I ran make topo/world-110m.json I got this file, which has the Chukchi Peninsula (and a tiny bit of Fiji) as separate polygons. 

Hope this helps!
